-- CampusHub 校园服务中心 数据库建表脚本
-- 共19张表

-- 1. 用户表
CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL COMMENT '用户名',
  password VARCHAR(100) NOT NULL COMMENT '密码(MD5)',
  nickname VARCHAR(50) COMMENT '昵称',
  email VARCHAR(100) COMMENT '邮箱',
  phone VARCHAR(20) COMMENT '手机号',
  avatar VARCHAR(255) COMMENT '头像URL',
  role VARCHAR(20) DEFAULT 'STUDENT' COMMENT '角色: STUDENT/CLUB_LEADER/ADMIN',
  status TINYINT DEFAULT 1 COMMENT '状态: 0禁用 1正常',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 2. 社团表
CREATE TABLE IF NOT EXISTS club (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL COMMENT '社团名称',
  description TEXT COMMENT '社团简介',
  category VARCHAR(50) COMMENT '分类: 学术/文艺/体育/公益/科技',
  logo VARCHAR(255) COMMENT '社团logo',
  leader_id BIGINT COMMENT '社长ID',
  member_count INT DEFAULT 0 COMMENT '成员数',
  status VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态: PENDING/APPROVED/REJECTED/DISBANDED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社团表';

-- 3. 社团成员表
CREATE TABLE IF NOT EXISTS club_member (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  club_id BIGINT NOT NULL COMMENT '社团ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role VARCHAR(20) DEFAULT 'MEMBER' COMMENT '角色: LEADER/MEMBER',
  status VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态: PENDING/APPROVED/REJECTED',
  join_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_club_user (club_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社团成员表';

-- 4. 竞赛表
CREATE TABLE IF NOT EXISTS competition (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL COMMENT '竞赛名称',
  description TEXT COMMENT '竞赛描述',
  organizer VARCHAR(100) COMMENT '主办方',
  level VARCHAR(20) COMMENT '级别: SCHOOL/PROVINCE/NATIONAL',
  register_deadline DATE COMMENT '报名截止日期',
  start_date DATE COMMENT '比赛开始日期',
  end_date DATE COMMENT '比赛结束日期',
  status VARCHAR(20) DEFAULT 'RECRUITING' COMMENT '状态: RECRUITING/IN_PROGRESS/FINISHED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='竞赛表';

-- 5. 竞赛队伍表
CREATE TABLE IF NOT EXISTS competition_team (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  competition_id BIGINT NOT NULL COMMENT '竞赛ID',
  name VARCHAR(100) NOT NULL COMMENT '队伍名称',
  leader_id BIGINT NOT NULL COMMENT '队长ID',
  description TEXT COMMENT '队伍描述/招募要求',
  member_count INT DEFAULT 1 COMMENT '当前成员数',
  max_members INT DEFAULT 5 COMMENT '最大人数',
  status VARCHAR(20) DEFAULT 'RECRUITING' COMMENT '状态: RECRUITING/FULL/REGISTERED/FINISHED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='竞赛队伍表';

-- 6. 队伍成员表
CREATE TABLE IF NOT EXISTS team_member (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  team_id BIGINT NOT NULL COMMENT '队伍ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role VARCHAR(20) DEFAULT 'MEMBER' COMMENT '角色: LEADER/MEMBER',
  join_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_team_user (team_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='队伍成员表';

-- 7. 活动表
CREATE TABLE IF NOT EXISTS activity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '活动标题',
  description TEXT COMMENT '活动详情',
  club_id BIGINT COMMENT '所属社团ID',
  location VARCHAR(200) COMMENT '活动地点',
  start_time DATETIME COMMENT '开始时间',
  end_time DATETIME COMMENT '结束时间',
  max_participants INT COMMENT '最大参与人数',
  current_participants INT DEFAULT 0 COMMENT '当前报名人数',
  cover_image VARCHAR(255) COMMENT '封面图',
  status VARCHAR(20) DEFAULT 'DRAFT' COMMENT '状态: DRAFT/PUBLISHED/REGISTERING/IN_PROGRESS/FINISHED/CANCELLED',
  organizer_id BIGINT COMMENT '组织者ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动表';

-- 8. 活动报名表
CREATE TABLE IF NOT EXISTS activity_registration (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_id BIGINT NOT NULL COMMENT '活动ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  status VARCHAR(20) DEFAULT 'REGISTERED' COMMENT '状态: REGISTERED/CANCELLED/CHECKED_IN',
  register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '报名时间',
  check_in_time DATETIME COMMENT '签到时间',
  UNIQUE KEY uk_activity_user (activity_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动报名表';

-- 9. 二手商品表
CREATE TABLE IF NOT EXISTS secondhand_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '商品标题',
  description TEXT COMMENT '商品描述',
  price DECIMAL(10,2) COMMENT '价格',
  category VARCHAR(50) COMMENT '分类: 教材/电子/生活用品/其他',
  images TEXT COMMENT '图片URL列表(JSON数组)',
  seller_id BIGINT NOT NULL COMMENT '卖家ID',
  buyer_id BIGINT COMMENT '买家ID',
  status VARCHAR(20) DEFAULT 'ON_SALE' COMMENT '状态: ON_SALE/RESERVED/SOLD/OFF_SHELF',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='二手商品表';

-- 10. 失物招领表
CREATE TABLE IF NOT EXISTS lost_found (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(20) NOT NULL COMMENT '类型: LOST(失物)/FOUND(招领)',
  title VARCHAR(200) NOT NULL COMMENT '标题',
  description TEXT COMMENT '描述',
  location VARCHAR(200) COMMENT '丢失/拾到地点',
  lost_date DATE COMMENT '丢失/拾到日期',
  images TEXT COMMENT '图片URL列表',
  publisher_id BIGINT NOT NULL COMMENT '发布人ID',
  finder_id BIGINT COMMENT '认领人ID',
  status VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态: PENDING/CLAIMED/RESOLVED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='失物招领表';

-- 11. 消息通知表
CREATE TABLE IF NOT EXISTS notification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '接收人ID',
  title VARCHAR(200) NOT NULL COMMENT '通知标题',
  content TEXT COMMENT '通知内容',
  type VARCHAR(30) COMMENT '类型: ACTIVITY_REMIND/CLUB_APPROVAL/SYSTEM/TRADE',
  ref_id BIGINT COMMENT '关联业务ID',
  is_read TINYINT DEFAULT 0 COMMENT '是否已读: 0未读 1已读',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消息通知表';

-- 12. 公告表
CREATE TABLE IF NOT EXISTS announcement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL COMMENT '公告标题',
  content TEXT COMMENT '公告内容',
  publisher_id BIGINT NOT NULL COMMENT '发布人ID',
  status VARCHAR(20) DEFAULT 'PUBLISHED' COMMENT '状态: DRAFT/PUBLISHED',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告表';

-- 13. 活动签到表
CREATE TABLE IF NOT EXISTS activity_checkin (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_id BIGINT NOT NULL COMMENT '活动ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  checkin_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '签到时间',
  checkin_method VARCHAR(20) COMMENT '签到方式: QR_CODE/MANUAL',
  UNIQUE KEY uk_activity_user (activity_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动签到表';

-- 14. 社团动态表
CREATE TABLE IF NOT EXISTS club_post (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  club_id BIGINT NOT NULL COMMENT '社团ID',
  user_id BIGINT NOT NULL COMMENT '发布人ID',
  title VARCHAR(200) COMMENT '标题',
  content TEXT COMMENT '内容',
  images TEXT COMMENT '图片列表',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社团动态表';

-- 15. 收藏表
CREATE TABLE IF NOT EXISTS favorite (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '用户ID',
  target_type VARCHAR(30) NOT NULL COMMENT '类型: ACTIVITY/SECONDHAND/LOST_FOUND',
  target_id BIGINT NOT NULL COMMENT '收藏对象ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_type_target (user_id, target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收藏表';

-- 16. 评论表
CREATE TABLE IF NOT EXISTS comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL COMMENT '评论人ID',
  target_type VARCHAR(30) NOT NULL COMMENT '类型: ACTIVITY/SECONDHAND/CLUB_POST',
  target_id BIGINT NOT NULL COMMENT '评论对象ID',
  content TEXT NOT NULL COMMENT '评论内容',
  parent_id BIGINT DEFAULT 0 COMMENT '父评论ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评论表';

-- 17. 文件表
CREATE TABLE IF NOT EXISTS file_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL COMMENT '文件名',
  file_path VARCHAR(500) NOT NULL COMMENT '存储路径',
  file_size BIGINT COMMENT '文件大小(字节)',
  file_type VARCHAR(50) COMMENT '文件类型',
  uploader_id BIGINT COMMENT '上传人ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件表';

-- 18. 操作日志表
CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT COMMENT '操作用户ID',
  module VARCHAR(50) COMMENT '操作模块',
  action VARCHAR(100) COMMENT '操作内容',
  method VARCHAR(200) COMMENT '请求方法',
  params TEXT COMMENT '请求参数',
  ip VARCHAR(50) COMMENT 'IP地址',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

-- 19. 数据统计宽表
CREATE TABLE IF NOT EXISTS stat_daily (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stat_date DATE NOT NULL COMMENT '统计日期',
  new_users INT DEFAULT 0 COMMENT '新增用户数',
  active_users INT DEFAULT 0 COMMENT '活跃用户数',
  new_activities INT DEFAULT 0 COMMENT '新增活动数',
  new_secondhand INT DEFAULT 0 COMMENT '新增二手数',
  new_clubs INT DEFAULT 0 COMMENT '新增社团数',
  UNIQUE KEY uk_date (stat_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日统计表';

-- 插入初始数据
INSERT INTO sys_user (username, password, nickname, role) VALUES 
('admin', 'e10adc3949ba59abbe56e057f20f883e', '管理员', 'ADMIN'),
('student', 'e10adc3949ba59abbe56e057f20f883e', '同学', 'STUDENT');

SELECT '所有19张表创建完成!' AS result;
